version: '3.8'

services:
    php:
        image: php:8.2-alpine
        container_name: php_app
        working_dir: /app
        volumes:
            - ./:/app
        command: tail -f /dev/null

    composer:
        image: composer:lts
        container_name: composer_app
        working_dir: /app
        volumes:
            - ./:/app
        command: tail -f /dev/null